### Variables 
@apiurl = http://localhost:5000

### GET users
GET {{apiurl}} HTTP/1.1

### POST createUser
POST {{apiurl}}/users/register HTTP/1.1
Content-Type: application/json

{
   "name":"Samuel",
   "email":"samuelspcunha@gmail.com",
   "phone": "11977925700",
   "password": "teste123",
   "confirmPassword": "teste123"
}




